### ISSUE TITLE
Error handling: make method to throw exceptions

### ISSUE THREAD

**Issue by fimion** [fimion/wheniwork-api-py#1]
Make this throw errors correctly

**Comment by nigeljyng** [comment]
Hello @fimion 

I use your wheniwork api code a lot, and would like to contribute. I've submitted a PR https://github.com/fimion/wheniwork-api-py/pull/3 that gets rid of the `asserts` and raises the actual error message. Please take a look 😀

**Comment by fimion** [comment]
This is great! thanks so much. I haven't had time to look at this recently, and you are absolutely right, that should not have been asserts. I'll work on getting a new version pushed up today. Thanks!

**Comment by nigeljyng** [comment]
@fimion If you don't have time some time next week I can submit a PR to bump the version and upload it to PyPI? would be nice to have this new version pip installable. 😀
