### ISSUE TITLE
Track development dependencies - requirements.txt or pipenv

### ISSUE THREAD

**Issue by fimion** [fimion/wheniwork-api-py#4]
We need to add a way to easily create a development environment for new contributors. The packages needed are : 
 - `requests`
 - `pytest`
 - `sphinx`
should we use pipenv or good old requirements.txt?

**Comment by nigeljyng** [comment]
We could do `requirements.txt` and `requirements-dev.txt`. Former will just have `requests`. Seems like the easiest way to go?

**Comment by fimion** [comment]
Yeah, i think pipenv is really meant more for applications or projects, and less so for libraries.

**Comment by fimion** [comment]
Fixed in #7
